/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as DocenciaRouteImport } from './routes/docencia'
import { Route as IndexRouteImport } from './routes/index'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenciaRoute = DocenciaRouteImport.update({
  id: '/docencia',
  path: '/docencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docencia': typeof DocenciaRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docencia': typeof DocenciaRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docencia': typeof DocenciaRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docencia' | '/proyectos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docencia' | '/proyectos'
  id: '__root__' | '/' | '/docencia' | '/proyectos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocenciaRoute: typeof DocenciaRoute
  ProyectosRoute: typeof ProyectosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docencia': {
      id: '/docencia'
      path: '/docencia'
      fullPath: '/docencia'
      preLoaderRoute: typeof DocenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocenciaRoute: DocenciaRoute,
  ProyectosRoute: ProyectosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
